# Generated by Django 5.2.5 on 2025-08-27 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('Food', 'Food (Groceries, Dining Out, Snacks, Beverages)'), ('Travel', 'Travel (Flights, Accommodation, Transport, Activities, Souvenirs)'), ('Bills', 'Bills (Electricity, Water, Gas, Internet, Phone, Insurance)'), ('Shopping', 'Shopping (Clothing, Electronics, Home Goods, Beauty Products, Toys)'), ('Health', 'Health (Doctor Visits, Medications, Therapy, Fitness)'), ('Entertainment', 'Entertainment (Movies, Concerts, Games, Hobbies, Books)'), ('Education', 'Education (Tuition, Books, Online Courses, Workshops, Student Loans)'), ('Rent', 'Rent (Apartment, Mortgage, Roommate Share, Storage, Parking)'), ('Utilities', 'Utilities (Electricity, Water, Gas, Internet, Trash Services)'), ('Misc', 'Miscellaneous (Gifts, Charity, Pet Care, Unexpected Repairs, Subscriptions)'), ('Transportation', 'Transportation (Fuel, Car Maintenance, Public Transport, Taxis)'), ('Taxes', 'Taxes (Income Tax, Property Tax, Sales Tax, Tax Penalties)'), ('Insurance', 'Insurance (Health, Life, Auto, Home, Travel)'), ('Debt Repayment', 'Debt Repayment (Credit Cards, Loans, Mortgages, Personal Loans)'), ('Childcare', 'Childcare (Daycare, Babysitting, School Fees, Activities)'), ('Maintenance', 'Maintenance (Home Repairs, Car Repairs, Appliance Replacement)'), ('Legal', 'Legal (Lawyer Fees, Court Costs, Legal Settlements)'), ('Gifts & Donations', 'Gifts & Donations (Birthday, Christmas, Charitable Donations)'), ('Pets', 'Pets (Food, Veterinary, Supplies, Boarding)'), ('Miscellaneous', 'Miscellaneous (Bank Fees, Unexpected Costs, Small Purchases)')], default='Misc', max_length=100)),
                ('ai_suggested_category', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'created_at'],
            },
        ),
    ]
