# Generated by Django 5.2.5 on 2025-08-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_alter_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(blank=True, choices=[('Food', 'Food (Groceries, Dining Out, Snacks, Beverages)'), ('Travel', 'Travel (Flights, Accommodation, Transport, Activities, Souvenirs)'), ('Bills', 'Bills (Electricity, Water, Gas, Internet, Phone, Insurance)'), ('Shopping', 'Shopping (Clothing, Electronics, Home Goods, Beauty Products, Toys)'), ('Health', 'Health (Doctor Visits, Medications, Therapy, Fitness)'), ('Entertainment', 'Entertainment (Movies, Concerts, Games, Hobbies, Books)'), ('Education', 'Education (Tuition, Books, Online Courses, Workshops, Student Loans)'), ('Rent', 'Rent (Apartment, Mortgage, Roommate Share, Storage, Parking)'), ('Utilities', 'Utilities (Electricity, Water, Gas, Internet, Trash Services)'), ('Transportation', 'Transportation (Fuel, Car Maintenance, Public Transport, Taxis)'), ('Taxes', 'Taxes (Income Tax, Property Tax, Sales Tax, Tax Penalties)'), ('Insurance', 'Insurance (Health, Life, Auto, Home, Travel)'), ('Debt Repayment', 'Debt Repayment (Credit Cards, Loans, Mortgages, Personal Loans)'), ('Childcare', 'Childcare (Daycare, Babysitting, School Fees, Activities)'), ('Maintenance', 'Maintenance (Home Repairs, Car Repairs, Appliance Replacement)'), ('Legal', 'Legal (Lawyer Fees, Court Costs, Legal Settlements)'), ('Gifts & Donations', 'Gifts & Donations (Birthday, Christmas, Charitable Donations)'), ('Pets', 'Pets (Food, Veterinary, Supplies, Boarding)'), ('Misc', 'Miscellaneous (Gifts, Charity, Pet Care, Unexpected Repairs, Subscriptions)')], max_length=100, null=True),
        ),
    ]
