# Generated by Django 5.2.5 on 2025-08-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_alter_expense_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='ai_suggested_category',
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(blank=True, choices=[('Food', 'Food'), ('Travel', 'Travel'), ('Bills', 'Bills'), ('Shopping', 'Shopping'), ('Health', 'Health'), ('Entertainment', 'Entertainment'), ('Education', 'Education'), ('Rent', 'Rent'), ('Utilities', 'Utilities'), ('Transportation', 'Transportation'), ('Taxes', 'Taxes'), ('Insurance', 'Insurance'), ('Debt Repayment', 'Debt Repayment'), ('Childcare', 'Childcare'), ('Maintenance', 'Maintenance'), ('Legal', 'Legal'), ('Gifts & Donations', 'Gifts & Donations'), ('Pets', 'Pets'), ('Miscellaneous', 'Miscellaneous')], max_length=100, null=True),
        ),
    ]
