# Generated by Django 5.2.5 on 2025-08-27 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('Salary', 'Salary'), ('Business', 'Business'), ('Investment', 'Investment'), ('Freelancing', 'Freelancing'), ('Rental Income', 'Rental Income'), ('Dividends', 'Dividends'), ('Interest', 'Interest'), ('Capital Gains', 'Capital Gains'), ('Pension', 'Pension'), ('Annuity', 'Annuity'), ('Social Security', 'Social Security'), ('Royalties', 'Royalties'), ('Gambling Winnings', 'Gambling Winnings'), ('Alimony', 'Alimony'), ('Child Support', 'Child Support'), ('Grants', 'Grants'), ('Scholarship', 'Scholarship'), ('Tax Refund', 'Tax Refund'), ('Sale of Assets', 'Sale of Assets'), ('Gift', 'Gift'), ('Inheritance', 'Inheritance'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
