# Generated by Django 5.2.5 on 2025-08-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='ai_suggested_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
