# Generated by Django 5.2.5 on 2025-08-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_income_ai_suggested_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.CharField(blank=True, choices=[('Salary', 'Salary'), ('Business', 'Business'), ('Investment', 'Investment'), ('Freelancing', 'Freelancing'), ('Rental Income', 'Rental Income'), ('Dividends', 'Dividends'), ('Interest', 'Interest'), ('Capital Gains', 'Capital Gains'), ('Pension', 'Pension'), ('Annuity', 'Annuity'), ('Social Security', 'Social Security'), ('Royalties', 'Royalties'), ('Gambling Winnings', 'Gambling Winnings'), ('Alimony', 'Alimony'), ('Child Support', 'Child Support'), ('Grants', 'Grants'), ('Scholarship', 'Scholarship'), ('Tax Refund', 'Tax Refund'), ('Sale of Assets', 'Sale of Assets'), ('Gift', 'Gift'), ('Inheritance', 'Inheritance'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
