# Generated by Django 5.2.5 on 2025-08-28 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0003_alter_income_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='ai_suggested_category',
        ),
    ]
